stages:
  - deploy

deploy_main:
  stage: deploy
  tags:
    - genix
  only:
    - main
  script:
    - cd /home/ubuntu/genix-front
    - git pull origin main
    - docker compose down
    - docker compose up -d --build
  environment:
    name: production
    url: https://app.genixerp.com

deploy_yuksalish:
  stage: deploy
  tags:
    - yuksalish-genix
  only:
    - yuksalish
  script:
    - cd /home/ubuntu/genix-front
    - git fetch origin
    - git checkout yuksalish
    - git pull origin yuksalish
    - docker compose down
    - docker compose up -d --build
  environment:
    name: yuksalish
    url: https://my.yuksalish.group
