stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - genix
  only:
    - main
  script:
    - cd /home/uz-user/genix-front
    - git pull origin main
    - docker compose down
    - docker compose up -d --build
  environment:
    name: production
    url: https://app.genixerp.com
