
import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Plus, Search, FileText, Calendar, DollarSign, CheckCircle, Clock, AlertCircle, Trash2, Edit, Download, Loader2, ChevronLeft, ChevronRight, RotateCcw, XCircle, Send, ArrowLeftRight, Filter, X, FileSpreadsheet } from "lucide-react";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from "@/components/ui/sheet";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { format } from "date-fns";
import { useLanguage } from "@/components/contexts/LanguageContext";
import { useTranslation } from "@/components/utils/translations";
import { useFinancials } from "@/components/contexts/FinancialsContext";
import { usePermissions } from "@/hooks/usePermissions";
import { useCurrencyFormatter } from '@/hooks/useCurrencyFormatter';
import { useAlertModal } from "@/hooks/useAlertModal";
import AlertModal from "@/components/shared/AlertModal";
import AccountCombobox from "@/components/shared/AccountCombobox";
import { MODULES } from "@/config/permissions";
import financeService from "@/api/services/finance";
import { generateDocumentPDF } from "@/components/shared/DocumentPrint";

// ── Journal Entry Description Translation ──────────────────────────────
// Patterns match English descriptions generated by the backend.
// Each pattern captures relevant details (order code, product name, qty, etc.)
// and maps them to a translation key with a custom formatter.

const JE_DESC_PATTERNS = [
  // Stock / Warehouse
  { en: /^Stock Operation:\s*(.+)$/, key: 'je_stock_op', fmt: (m) => ({ ref: m[1] }) },

  // Sales — with customer name
  { en: /^Sales Invoice\s+(.+?)\s+\(repair\)$/, key: 'je_sales_invoice_repair', fmt: (m) => ({ ref: m[1] }) },
  { en: /^Sales Invoice\s+(\S+)\s+[—–-]\s+(.+)$/, key: 'je_sales_invoice_cust', fmt: (m) => ({ ref: m[1], customer: m[2] }) },
  { en: /^Sales Invoice\s+(.+)$/, key: 'je_sales_invoice', fmt: (m) => ({ ref: m[1] }) },

  // Vendor / Purchase — with vendor name
  { en: /^Vendor Bill\s+(\S+)\s+[—–-]\s+(.+)$/, key: 'je_vendor_bill_detail', fmt: (m) => ({ ref: m[1], vendor: m[2] }) },
  { en: /^Vendor Bill\s+(.+)$/, key: 'je_vendor_bill', fmt: (m) => ({ ref: m[1] }) },
  { en: /^Bill:\s*(.+)$/, key: 'je_vendor_bill_name', fmt: (m) => ({ vendor: m[1] }) },

  // Production Orders — with product name; keep more specific patterns first
  { en: /^Production Order\s+(\S+)\s+completed\s*-\s*(.+?)\s*\(qty:\s*([\d.]+)\)$/, key: 'je_prod_completed', fmt: (m) => ({ code: m[1], product: m[2], qty: m[3] }) },
  { en: /^Production Order\s+(\S+)\s+started\s*-\s*(.+?)\s*-\s*materials consumed$/, key: 'je_prod_started_product', fmt: (m) => ({ code: m[1], product: m[2] }) },
  { en: /^Production Order\s+(\S+)\s+started\s*-\s*materials consumed$/, key: 'je_prod_started', fmt: (m) => ({ code: m[1] }) },
  { en: /^Production Order\s+(\S+)\s+confirmed\s*-\s*(.+?)\s*-\s*planned material cost$/, key: 'je_prod_confirmed_product', fmt: (m) => ({ code: m[1], product: m[2] }) },
  { en: /^Production Order\s+(\S+)\s+confirmed\s*-\s*planned material cost$/, key: 'je_prod_confirmed', fmt: (m) => ({ code: m[1] }) },

  // Inventory
  { en: /^Inventory Adjustment\s*-\s*(.+)$/, key: 'je_inv_adjustment', fmt: (m) => ({ reason: m[1] }) },
  { en: /^Inventory Adjustment$/, key: 'je_inv_adjustment_no_reason', fmt: () => ({}) },
  { en: /^Inventory Count Adjustment:\s*(.+)$/, key: 'je_inv_count', fmt: (m) => ({ ref: m[1] }) },
  { en: /^Scrap Order:\s*(.+)$/, key: 'je_scrap', fmt: (m) => ({ ref: m[1] }) },

  // Fixed Assets
  { en: /^Fixed Asset Acquisition:\s*(.+?)\s*-\s*(.+)$/, key: 'je_fixed_asset', fmt: (m) => ({ code: m[1], name: m[2] }) },
  { en: /^Fixed Asset Acquisition:\s*(.+)$/, key: 'je_fixed_asset_simple', fmt: (m) => ({ ref: m[1] }) },
  { en: /^Asset Disposal\s*\((\w+)\):\s*(.+)$/, key: 'je_asset_disposal', fmt: (m) => ({ reason: m[1], name: m[2] }) },
  { en: /^Depreciation\s+(.+)$/, key: 'je_depreciation', fmt: (m) => ({ period: m[1] }) },

  // Expense
  { en: /^Expense:\s*(\S+)\s*-\s*(.+)$/, key: 'je_expense_detail', fmt: (m) => ({ ref: m[1], desc: m[2] }) },
  { en: /^Expense:\s*(.+)$/, key: 'je_expense', fmt: (m) => ({ ref: m[1] }) },

  // Payroll
  { en: /^Salary Payment:\s*(.+?)\s*\((.+)\)$/, key: 'je_salary', fmt: (m) => ({ period: m[1], method: m[2] }) },

  // Payments — with vendor name
  { en: /^Payment for invoice\s+(\S+)\s+[—–-]\s+(.+)$/, key: 'je_payment_invoice_vendor', fmt: (m) => ({ ref: m[1], vendor: m[2] }) },
  { en: /^Payment for invoice\s+(.+)$/, key: 'je_payment_invoice', fmt: (m) => ({ ref: m[1] }) },

  // Bank Reconciliation
  { en: /^Bank reconciliation clearing\s*-\s*receipts\s*\((.+)\)$/, key: 'je_bank_recon_receipts', fmt: (m) => ({ date: m[1] }) },
  { en: /^Bank reconciliation clearing\s*-\s*payments\s*\((.+)\)$/, key: 'je_bank_recon_payments', fmt: (m) => ({ date: m[1] }) },
  { en: /^Reconciliation write-off\s*\(([\d.-]+)\)\s*-\s*(.+)$/, key: 'je_recon_writeoff', fmt: (m) => ({ amount: m[1], date: m[2] }) },

  // Reversal
  { en: /^Teskari:\s*(.+)$/, key: 'je_reversal', fmt: (m) => ({ ref: m[1] }) },
];

const JE_DESC_LABELS = {
  // Stock / Warehouse
  je_stock_op:               { en: (d) => `Stock Operation: ${d.ref}`,
                                uz: (d) => `Ombor operatsiyasi: ${d.ref}`,
                                ru: (d) => `Складская операция: ${d.ref}` },
  // Sales
  je_sales_invoice:          { en: (d) => `Sales Invoice: ${d.ref}`,
                                uz: (d) => `Sotuv hisob-fakturasi: ${d.ref}`,
                                ru: (d) => `Счёт-фактура продажи: ${d.ref}` },
  je_sales_invoice_cust:     { en: (d) => `Sales Invoice: ${d.ref} — ${d.customer}`,
                                uz: (d) => `Sotuv hisob-fakturasi: ${d.ref} — ${d.customer}`,
                                ru: (d) => `Счёт-фактура продажи: ${d.ref} — ${d.customer}` },
  je_sales_invoice_repair:   { en: (d) => `Sales Invoice (repair): ${d.ref}`,
                                uz: (d) => `Sotuv hisob-fakturasi (ta'mirlash): ${d.ref}`,
                                ru: (d) => `Счёт-фактура (ремонт): ${d.ref}` },
  // Vendor / Purchase
  je_vendor_bill:            { en: (d) => `Vendor Bill: ${d.ref}`,
                                uz: (d) => `Yetkazib beruvchi hisob-fakturasi: ${d.ref}`,
                                ru: (d) => `Счёт поставщика: ${d.ref}` },
  je_vendor_bill_detail:     { en: (d) => `Vendor Bill: ${d.ref} — ${d.vendor}`,
                                uz: (d) => `Yetkazib beruvchi hisob-fakturasi: ${d.ref} — ${d.vendor}`,
                                ru: (d) => `Счёт поставщика: ${d.ref} — ${d.vendor}` },
  je_vendor_bill_name:       { en: (d) => `Vendor Bill: ${d.vendor}`,
                                uz: (d) => `Yetkazib beruvchi hisob-fakturasi: ${d.vendor}`,
                                ru: (d) => `Счёт поставщика: ${d.vendor}` },
  // Production Orders
  je_prod_confirmed:         { en: (d) => `Production Order ${d.code} confirmed — planned material cost`,
                                uz: (d) => `Ishlab chiqarish buyurtmasi ${d.code} tasdiqlandi — rejalashtirilgan material xarajati`,
                                ru: (d) => `Производственный заказ ${d.code} подтверждён — плановая стоимость материалов` },
  je_prod_confirmed_product: { en: (d) => `Production Order ${d.code} confirmed — ${d.product} — planned material cost`,
                                uz: (d) => `Ishlab chiqarish buyurtmasi ${d.code} tasdiqlandi — ${d.product} — rejalashtirilgan material xarajati`,
                                ru: (d) => `Производственный заказ ${d.code} подтверждён — ${d.product} — плановая стоимость материалов` },
  je_prod_started:           { en: (d) => `Production Order ${d.code} started — materials consumed`,
                                uz: (d) => `Ishlab chiqarish buyurtmasi ${d.code} boshlandi — materiallar sarflandi`,
                                ru: (d) => `Производственный заказ ${d.code} начат — материалы списаны` },
  je_prod_started_product:   { en: (d) => `Production Order ${d.code} started — ${d.product} — materials consumed`,
                                uz: (d) => `Ishlab chiqarish buyurtmasi ${d.code} boshlandi — ${d.product} — materiallar sarflandi`,
                                ru: (d) => `Производственный заказ ${d.code} начат — ${d.product} — материалы списаны` },
  je_prod_completed:         { en: (d) => `Production Order ${d.code} completed — ${d.product} (qty: ${d.qty})`,
                                uz: (d) => `Ishlab chiqarish buyurtmasi ${d.code} yakunlandi — ${d.product} (miqdor: ${d.qty})`,
                                ru: (d) => `Производственный заказ ${d.code} завершён — ${d.product} (кол-во: ${d.qty})` },
  // Inventory
  je_inv_adjustment:         { en: (d) => `Inventory Adjustment — ${d.reason}`,
                                uz: (d) => `Inventarizatsiya tuzatishi — ${d.reason}`,
                                ru: (d) => `Корректировка запасов — ${d.reason}` },
  je_inv_adjustment_no_reason: { en: () => `Inventory Adjustment`,
                                uz: () => `Inventarizatsiya tuzatishi`,
                                ru: () => `Корректировка запасов` },
  je_inv_count:              { en: (d) => `Inventory Count Adjustment: ${d.ref}`,
                                uz: (d) => `Inventarizatsiya hisob tuzatishi: ${d.ref}`,
                                ru: (d) => `Корректировка по инвентаризации: ${d.ref}` },
  je_scrap:                  { en: (d) => `Scrap Order: ${d.ref}`,
                                uz: (d) => `Yaroqsizlik buyurtmasi: ${d.ref}`,
                                ru: (d) => `Списание: ${d.ref}` },
  // Fixed Assets
  je_fixed_asset:            { en: (d) => `Fixed Asset Acquisition: ${d.code} — ${d.name}`,
                                uz: (d) => `Asosiy vosita sotib olish: ${d.code} — ${d.name}`,
                                ru: (d) => `Приобретение ОС: ${d.code} — ${d.name}` },
  je_fixed_asset_simple:     { en: (d) => `Fixed Asset Acquisition: ${d.ref}`,
                                uz: (d) => `Asosiy vosita sotib olish: ${d.ref}`,
                                ru: (d) => `Приобретение ОС: ${d.ref}` },
  je_asset_disposal:         { en: (d) => `Asset Disposal (${d.reason}): ${d.name}`,
                                uz: (d) => { const r = { sold: 'sotildi', destroyed: 'buzildi', expired: 'eskirdi', stolen: "o'g'irlandi" }[d.reason] || d.reason; return `Asosiy vosita chiqarish (${r}): ${d.name}`; },
                                ru: (d) => { const r = { sold: 'продано', destroyed: 'уничтожено', expired: 'истекло', stolen: 'украдено' }[d.reason] || d.reason; return `Выбытие ОС (${r}): ${d.name}`; } },
  je_depreciation:           { en: (d) => `Depreciation: ${d.period}`,
                                uz: (d) => `Amortizatsiya: ${d.period}`,
                                ru: (d) => `Амортизация: ${d.period}` },
  // Expense
  je_expense:                { en: (d) => `Expense: ${d.ref}`,
                                uz: (d) => `Xarajat: ${d.ref}`,
                                ru: (d) => `Расход: ${d.ref}` },
  je_expense_detail:         { en: (d) => `Expense: ${d.ref} — ${d.desc}`,
                                uz: (d) => `Xarajat: ${d.ref} — ${d.desc}`,
                                ru: (d) => `Расход: ${d.ref} — ${d.desc}` },
  // Payroll
  je_salary:                 { en: (d) => `Salary Payment: ${d.period} (${d.method})`,
                                uz: (d) => { const m = { cash: 'naqd', bank_transfer: 'bank', card: 'karta' }[d.method] || d.method; return `Ish haqi to'lovi: ${d.period} (${m})`; },
                                ru: (d) => { const m = { cash: 'наличные', bank_transfer: 'банк', card: 'карта' }[d.method] || d.method; return `Выплата зарплаты: ${d.period} (${m})`; } },
  // Payments
  je_payment_invoice:        { en: (d) => `Payment for invoice ${d.ref}`,
                                uz: (d) => `Hisob-faktura uchun to'lov ${d.ref}`,
                                ru: (d) => `Оплата по счёту ${d.ref}` },
  je_payment_invoice_vendor: { en: (d) => `Payment for invoice ${d.ref} — ${d.vendor}`,
                                uz: (d) => `Hisob-faktura uchun to'lov ${d.ref} — ${d.vendor}`,
                                ru: (d) => `Оплата по счёту ${d.ref} — ${d.vendor}` },
  // Bank Reconciliation
  je_bank_recon_receipts:    { en: (d) => `Bank reconciliation — receipts (${d.date})`,
                                uz: (d) => `Bank solishtirma — tushumlar (${d.date})`,
                                ru: (d) => `Банковская сверка — поступления (${d.date})` },
  je_bank_recon_payments:    { en: (d) => `Bank reconciliation — payments (${d.date})`,
                                uz: (d) => `Bank solishtirma — to'lovlar (${d.date})`,
                                ru: (d) => `Банковская сверка — платежи (${d.date})` },
  je_recon_writeoff:         { en: (d) => `Reconciliation write-off (${d.amount}) — ${d.date}`,
                                uz: (d) => `Solishtirma hisobdan chiqarish (${d.amount}) — ${d.date}`,
                                ru: (d) => `Списание при сверке (${d.amount}) — ${d.date}` },
  // Reversal
  je_reversal:               { en: (d) => `Reversal: ${d.ref}`,
                                uz: (d) => `Teskari yozuv: ${d.ref}`,
                                ru: (d) => `Сторнирование: ${d.ref}` },
};

function translateJEDescription(description, language) {
  if (!description) return description;
  for (const { en, key, fmt } of JE_DESC_PATTERNS) {
    const match = description.match(en);
    if (match) {
      const data = fmt(match);
      const labelFn = JE_DESC_LABELS[key]?.[language] || JE_DESC_LABELS[key]?.en;
      if (typeof labelFn === 'function') return labelFn(data);
      return description;
    }
  }
  return description;
}

// ── Journal Name Translation Helper ──────────────────────────────────
// The backend now returns name (Russian), name_uz, name_en for each journal.
// This helper picks the correct one based on the current UI language.
function getJournalName(journal, language) {
  if (!journal) return '-';
  if (language === 'uz') return journal.name_uz || journal.name || '-';
  if (language === 'en') return journal.name_en || journal.name || '-';
  // Default (ru) uses journal.name which is the Russian name
  return journal.name || '-';
}

export default function GeneralLedger() {
  const { language } = useLanguage();
  const { t } = useTranslation(language);
  const {
    journalEntries,
    createJournalEntry,
    updateJournalEntry,
    deleteJournalEntry,
    cancelJournalEntry,
    postJournalEntry,
    reverseJournalEntry,
    resetJournalEntryToDraft,
    getJournalLines,
    accounts,
    journals,
    isLoading
  } = useFinancials();
  const { canCreate, isSuperAdmin } = usePermissions();
  const { formatCurrency } = useCurrencyFormatter();
  const { modal, showAlert, showError, showSuccess, close } = useAlertModal();

  const [filteredEntries, setFilteredEntries] = useState([]);
  const [searchQuery, setSearchQuery] = useState("");
  const [dateFrom, setDateFrom] = useState("");
  const [dateTo, setDateTo] = useState("");
  const [codeFilter, setCodeFilter] = useState("");
  const [showFilters, setShowFilters] = useState(false);
  const [currentPage, setCurrentPage] = useState(1);
  const pageSize = 50;
  const [selectedEntry, setSelectedEntry] = useState(null);
  const [selectedJournalLines, setSelectedJournalLines] = useState([]);
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [showReverseModal, setShowReverseModal] = useState(false);
  const [editingEntryId, setEditingEntryId] = useState(null);
  const [isSaving, setIsSaving] = useState(false);
  const [isActionLoading, setIsActionLoading] = useState(false);
  const [auditLogs, setAuditLogs] = useState([]);

  // Format number with space thousand separators inline
  const formatNumberInline = (value) => {
    if (!value && value !== 0) return '';
    const str = String(value).replace(/[^0-9.]/g, '');
    if (!str) return '';
    const parts = str.split('.');
    parts[0] = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, ' ');
    return parts.length > 1 ? `${parts[0]}.${parts[1]}` : parts[0];
  };
  const parseFormattedNumber = (value) => String(value).replace(/\s/g, '');

  // Reverse modal state
  const [reverseDate, setReverseDate] = useState(new Date().toISOString().split('T')[0]);
  const [reverseReason, setReverseReason] = useState('');

  const defaultJournalId = journals.find(j => j.code === 'MISC')?.id || journals.find(j => j.code === 'GEN')?.id || journals[0]?.id || '';

  const emptyEntry = {
    journal_id: '',
    entry_date: new Date().toISOString().split('T')[0],
    description: '',
    reference: '',
    tags: [],
    lines: [
      { account_id: '', description: '', debit_amount: 0, credit_amount: 0 },
      { account_id: '', description: '', debit_amount: 0, credit_amount: 0 }
    ]
  };

  const [newEntry, setNewEntry] = useState(emptyEntry);

  useEffect(() => {
    setFilteredEntries(journalEntries);
  }, [journalEntries]);

  useEffect(() => {
    let filtered = journalEntries;
    if (searchQuery) {
      const q = searchQuery.toLowerCase();
      filtered = filtered.filter(entry =>
        entry.description?.toLowerCase().includes(q) ||
        entry.entry_number?.toLowerCase().includes(q) ||
        entry.reference?.toLowerCase().includes(q) ||
        entry.source_type?.toLowerCase().includes(q) ||
        getJournalName(entry.journal, language)?.toLowerCase().includes(q)
      );
    }
    if (dateFrom) {
      filtered = filtered.filter(entry => {
        const d = entry.entry_date?.split('T')[0];
        return d && d >= dateFrom;
      });
    }
    if (dateTo) {
      filtered = filtered.filter(entry => {
        const d = entry.entry_date?.split('T')[0];
        return d && d <= dateTo;
      });
    }
    if (codeFilter) {
      const cf = codeFilter.toLowerCase();
      filtered = filtered.filter(entry =>
        entry.entry_number?.toLowerCase().includes(cf)
      );
    }
    setFilteredEntries(filtered);
    setCurrentPage(1);
  }, [searchQuery, dateFrom, dateTo, codeFilter, journalEntries]);

  const activeFilterCount = (dateFrom ? 1 : 0) + (dateTo ? 1 : 0) + (codeFilter ? 1 : 0);
  const clearFilters = () => { setDateFrom(''); setDateTo(''); setCodeFilter(''); setSearchQuery(''); };

  const [isLoadingLines, setIsLoadingLines] = useState(false);

  const handleSelectEntry = async (entry) => {
    setSelectedEntry(entry);
    setSelectedJournalLines([]);
    setAuditLogs([]);
    setIsLoadingLines(true);
    try {
      const [fullEntry, logs] = await Promise.all([
        financeService.getJournalEntry(entry.id),
        financeService.getJournalEntryAuditLogs(entry.id).catch(() => []),
      ]);
      if (fullEntry) {
        setSelectedEntry(fullEntry);
        setSelectedJournalLines(fullEntry.lines || []);
      } else {
        const lines = getJournalLines(entry.id);
        setSelectedJournalLines(lines);
      }
      setAuditLogs(logs || []);
    } catch (err) {
      console.error('Failed to fetch journal entry lines:', err);
      const lines = getJournalLines(entry.id);
      setSelectedJournalLines(lines);
    } finally {
      setIsLoadingLines(false);
    }
  };

  const processLines = (lines) => {
    const validLines = lines.filter(line =>
      line.account_id && (parseFloat(line.debit_amount) > 0 || parseFloat(line.credit_amount) > 0)
    );

    if (validLines.length < 2) return null;

    const processedLines = [];
    for (const line of validLines) {
      const debit = parseFloat(line.debit_amount) || 0;
      const credit = parseFloat(line.credit_amount) || 0;
      if (debit > 0 && credit > 0) {
        processedLines.push({ account_id: line.account_id, description: line.description || '', debit_amount: debit, credit_amount: 0 });
        processedLines.push({ account_id: line.account_id, description: line.description || '', debit_amount: 0, credit_amount: credit });
      } else if (debit > 0 || credit > 0) {
        processedLines.push({ account_id: line.account_id, description: line.description || '', debit_amount: debit, credit_amount: credit });
      }
    }
    return processedLines.length >= 2 ? processedLines : null;
  };

  const handleCreateEntry = async () => {
    setIsSaving(true);
    try {
      if (!newEntry.description?.trim()) {
        showError(t('description_required') || 'Description is required');
        setIsSaving(false);
        return;
      }

      const processedLines = processLines(newEntry.lines);
      if (!processedLines) {
        showError(t('minimum_two_lines_required'));
        setIsSaving(false);
        return;
      }

      const totalDebitCheck = processedLines.reduce((sum, l) => sum + l.debit_amount, 0);
      const totalCreditCheck = processedLines.reduce((sum, l) => sum + l.credit_amount, 0);
      if (Math.abs(totalDebitCheck - totalCreditCheck) > 0.01) {
        showError(t('debits_must_equal_credits'));
        setIsSaving(false);
        return;
      }

      const entryData = {
        journal_id: newEntry.journal_id,
        entry_date: newEntry.entry_date,
        description: newEntry.description,
        reference: newEntry.reference,
        tags: newEntry.tags?.length ? newEntry.tags : undefined,
        lines: processedLines
      };

      if (editingEntryId) {
        await updateJournalEntry(editingEntryId, entryData);
      } else {
        await createJournalEntry(entryData);
      }

      resetForm();
      setShowCreateModal(false);
    } catch (error) {
      console.error('Error saving journal entry:', error);
      const msg = error?.response?.data?.error?.message || error?.response?.data?.message || error?.message || 'Failed to save journal entry';
      showError(msg);
    } finally {
      setIsSaving(false);
    }
  };

  const resetForm = () => {
    setNewEntry({ ...emptyEntry, journal_id: defaultJournalId });
    setEditingEntryId(null);
  };

  const addLine = () => {
    setNewEntry(prev => ({
      ...prev,
      lines: [...prev.lines, { account_id: '', description: '', debit_amount: 0, credit_amount: 0 }]
    }));
  };

  const removeLine = (index) => {
    if (newEntry.lines.length <= 2) return;
    setNewEntry(prev => ({
      ...prev,
      lines: prev.lines.filter((_, i) => i !== index)
    }));
  };

  const updateLine = (index, field, value) => {
    setNewEntry(prev => ({
      ...prev,
      lines: prev.lines.map((line, i) => {
        if (i !== index) return line;
        const updated = { ...line, [field]: value };
        if (field === 'debit_amount' && parseFloat(value) > 0) {
          updated.credit_amount = 0;
        } else if (field === 'credit_amount' && parseFloat(value) > 0) {
          updated.debit_amount = 0;
        }
        return updated;
      })
    }));
  };

  const handleEditEntry = () => {
    if (!selectedEntry) return;
    if (selectedEntry.status !== 'draft') {
      showError(t('cannot_edit_posted_entry') || 'Only draft entries can be edited.');
      return;
    }
    setEditingEntryId(selectedEntry.id);
    setNewEntry({
      journal_id: selectedEntry.journal_id || '',
      entry_date: selectedEntry.entry_date ? new Date(selectedEntry.entry_date).toISOString().split('T')[0] : new Date().toISOString().split('T')[0],
      description: selectedEntry.description || '',
      reference: selectedEntry.reference || '',
      tags: selectedEntry.tags || [],
      lines: selectedJournalLines.length > 0
        ? selectedJournalLines.map(line => ({
            account_id: line.account_id || '',
            description: line.description || '',
            debit_amount: line.debit_amount || 0,
            credit_amount: line.credit_amount || 0,
          }))
        : [
            { account_id: '', description: '', debit_amount: 0, credit_amount: 0 },
            { account_id: '', description: '', debit_amount: 0, credit_amount: 0 }
          ]
    });
    setShowCreateModal(true);
  };

  const handlePostEntry = async () => {
    if (!selectedEntry || selectedEntry.status !== 'draft') return;
    setIsActionLoading(true);
    try {
      await postJournalEntry(selectedEntry.id);
      setSelectedEntry(prev => prev ? { ...prev, status: 'posted' } : prev);
      showSuccess(t('entry_posted_successfully') || 'Journal entry posted successfully');
    } catch (error) {
      let msg = error?.response?.data?.error?.message || error?.response?.data?.message || error?.message || 'Failed to post entry';
      // Translate insufficient balance error from backend
      const balanceMatch = msg.match(/^(.+?)\s*\((\d+)\)\s*hisobida mablag[''] yetarli emas\.\s*Joriy balans:\s*(.+?)\s*so'm$/);
      if (balanceMatch) {
        const [, name, code, balance] = balanceMatch;
        msg = t('insufficient_account_balance')
          ? t('insufficient_account_balance').replace('{name}', name).replace('{code}', code).replace('{balance}', balance)
          : `Insufficient funds in ${name} (${code}). Current balance: ${balance} so'm`;
      }
      showError(msg);
    } finally {
      setIsActionLoading(false);
    }
  };

  const handleResetToDraft = async () => {
    if (!selectedEntry || selectedEntry.status !== 'posted') return;
    setIsActionLoading(true);
    try {
      await resetJournalEntryToDraft(selectedEntry.id);
      setSelectedEntry(prev => prev ? { ...prev, status: 'draft', posted_at: null } : prev);
      showSuccess(t('entry_reset_to_draft') || 'Yozuv qoralamaga qaytarildi — endi tahrirlash mumkin');
    } catch (error) {
      const msg = error?.response?.data?.error?.message || error?.message || 'Failed to reset entry';
      showError(msg);
    } finally {
      setIsActionLoading(false);
    }
  };

  const handleCancelEntry = async () => {
    if (!selectedEntry || selectedEntry.status !== 'draft') return;
    setIsActionLoading(true);
    try {
      await cancelJournalEntry(selectedEntry.id);
      setSelectedEntry(prev => prev ? { ...prev, status: 'cancelled' } : prev);
      showSuccess(t('entry_cancelled_successfully') || 'Journal entry cancelled');
    } catch (error) {
      const msg = error?.response?.data?.error?.message || error?.message || 'Failed to cancel entry';
      showError(msg);
    } finally {
      setIsActionLoading(false);
    }
  };

  const handleDeleteEntry = async () => {
    if (!selectedEntry || selectedEntry.status !== 'cancelled') return;
    setIsActionLoading(true);
    try {
      await deleteJournalEntry(selectedEntry.id);
      setSelectedEntry(null);
      setSelectedJournalLines([]);
      showSuccess(t('entry_deleted_successfully') || 'Journal entry deleted');
    } catch (error) {
      const msg = error?.response?.data?.error?.message || error?.message || 'Failed to delete entry';
      showError(msg);
    } finally {
      setIsActionLoading(false);
    }
  };

  const openReverseModal = () => {
    if (!selectedEntry || selectedEntry.status !== 'posted') return;
    setReverseDate(new Date().toISOString().split('T')[0]);
    setReverseReason('');
    setShowReverseModal(true);
  };

  const handleReverseEntry = async () => {
    if (!selectedEntry) return;
    setIsActionLoading(true);
    try {
      await reverseJournalEntry(selectedEntry.id, {
        date: reverseDate,
        reason: reverseReason
      });
      setShowReverseModal(false);
      setSelectedEntry(null);
      setSelectedJournalLines([]);
      showSuccess(t('reversal_created_successfully') || 'Reversal entry created as draft');
    } catch (error) {
      const msg = error?.response?.data?.error?.message || error?.message || 'Failed to reverse entry';
      showError(msg);
    } finally {
      setIsActionLoading(false);
    }
  };

  const handleViewPDF = () => {
    if (!selectedEntry) return;
    const lines = selectedJournalLines.map(line => ({
      account: line.account ? `${line.account.code} - ${line.account.name}` : (line.account_code ? `${line.account_code} - ${line.account_name}` : '-'),
      description: line.description || '-',
      debit: line.debit_amount > 0 ? formatCurrency(line.debit_amount) : '-',
      credit: line.credit_amount > 0 ? formatCurrency(line.credit_amount) : '-',
    }));

    const statusMap = {
      posted: t('posted') || 'Posted',
      draft: t('draft') || 'Draft',
      cancelled: t('cancelled') || 'Cancelled',
      reversed: t('reversed') || 'Reversed',
    };

    const doc = generateDocumentPDF({
      template: 'invoice',
      title: t('journal_entry') || 'Buxgalteriya yozuvi',
      documentNumber: selectedEntry.entry_number,
      documentDate: selectedEntry.entry_date ? format(new Date(selectedEntry.entry_date), 'dd.MM.yyyy') : '',
      dateLabel: t('date') || 'Date',
      headerFields: [
        { label: t('description') || 'Description', value: translateJEDescription(selectedEntry.description, language) || '-' },
        { label: t('status') || 'Status', value: statusMap[selectedEntry.status] || selectedEntry.status || '-' },
        { label: t('reference') || 'Reference', value: selectedEntry.reference || '-' },
        { label: t('total') || 'Total', value: formatCurrency(selectedEntry.total_debit || 0) },
      ],
      tableColumns: [
        { key: 'account', label: t('account') || 'Account', width: 55 },
        { key: 'description', label: t('description') || 'Description', width: 55 },
        { key: 'debit', label: t('debit') || 'Debit', align: 'right', width: 35 },
        { key: 'credit', label: t('credit') || 'Credit', align: 'right', width: 35 },
      ],
      tableData: lines,
      totals: [
        { label: `${t('total')} ${t('debit')}`, value: formatCurrency(selectedEntry.total_debit || 0), bold: true },
        { label: `${t('total')} ${t('credit')}`, value: formatCurrency(selectedEntry.total_credit || 0), bold: true },
      ],
    });
    doc.save(`${selectedEntry.entry_number || 'journal-entry'}.pdf`);
  };

  // Export to Excel with beautiful styling using ExcelJS
  const handleExportExcel = async () => {
    const ExcelJS = await import('exceljs');
    const wb = new ExcelJS.Workbook();
    wb.creator = 'GenixERP';
    wb.created = new Date();

    const sheetName = (t('journal_entries') || 'Jurnal yozuvlari').substring(0, 31);
    const ws = wb.addWorksheet(sheetName, {
      pageSetup: { paperSize: 9, orientation: 'landscape', fitToPage: true, fitToWidth: 1, fitToHeight: 0 },
    });

    // Palette
    const BRAND_BLUE = '4F46E5';
    const HEADER_BG = '1E3A5F';
    const HEADER_FG = 'FFFFFF';
    const BORDER_CLR = 'CBD5E1';
    const STRIPE_BG = 'F8FAFC';
    const TOTAL_BG = 'EEF2FF';

    const thin = { style: 'thin', color: { argb: BORDER_CLR } };
    const borders = { top: thin, bottom: thin, left: thin, right: thin };
    const thickTop = { style: 'medium', color: { argb: BRAND_BLUE } };

    // Column widths
    ws.columns = [
      { width: 5.5 },   // A — №
      { width: 13 },    // B — Date
      { width: 24 },    // C — Number/Code
      { width: 52 },    // D — Description
      { width: 20 },    // E — Journal
      { width: 20 },    // F — Debit
      { width: 20 },    // G — Credit
      { width: 13 },    // H — Status
    ];

    const data = filteredEntries;
    const periodText = `${dateFrom || '...'} — ${dateTo || '...'}`;

    // ── Title row ──
    const titleRow = ws.addRow([t('journal_entries') || 'Jurnal yozuvlari']);
    ws.mergeCells(`A${titleRow.number}:H${titleRow.number}`);
    titleRow.getCell(1).font = { bold: true, size: 16, color: { argb: '1E293B' } };
    titleRow.getCell(1).alignment = { vertical: 'middle' };
    titleRow.height = 30;

    // ── Subtitle row ──
    const subRow = ws.addRow([`${periodText}  •  ${data.length} ${t('entries_total') || 'yozuv'}`]);
    ws.mergeCells(`A${subRow.number}:H${subRow.number}`);
    subRow.getCell(1).font = { size: 10, color: { argb: '64748B' } };
    subRow.height = 18;

    // ── Empty spacer ──
    ws.addRow([]);

    // ── Header row ──
    const headers = ['№', t('date') || 'Sana', t('number') || 'Raqam', t('description') || 'Tavsif', t('journal') || 'Jurnal', t('debit') || 'Debet', t('credit') || 'Kredit', t('status') || 'Holat'];
    const headerRow = ws.addRow(headers);
    headerRow.height = 26;
    headerRow.eachCell((cell) => {
      cell.font = { bold: true, size: 11, color: { argb: HEADER_FG } };
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: HEADER_BG } };
      cell.alignment = { horizontal: 'center', vertical: 'middle' };
      cell.border = borders;
    });
    // Debit/Credit headers right-aligned
    headerRow.getCell(6).alignment = { horizontal: 'right', vertical: 'middle' };
    headerRow.getCell(7).alignment = { horizontal: 'right', vertical: 'middle' };

    // ── Data rows ──
    let sumDebit = 0, sumCredit = 0;
    data.forEach((entry, idx) => {
      const d = entry.total_debit || 0;
      const cr = entry.total_credit || 0;
      sumDebit += d;
      sumCredit += cr;
      const isStripe = idx % 2 === 1;

      const row = ws.addRow([
        idx + 1,
        entry.entry_date ? format(new Date(entry.entry_date), 'dd.MM.yyyy') : '-',
        entry.entry_number || '-',
        translateJEDescription(entry.description || entry.reference, language) || '-',
        getJournalName(entry.journal, language),
        d,
        cr,
        entry.reversed_entry_id ? (t('reversed') || 'reversed') : (entry.status || '-'),
      ]);

      row.eachCell((cell, colNumber) => {
        cell.font = { size: 10 };
        cell.border = borders;
        cell.alignment = { vertical: 'middle' };
        if (isStripe) {
          cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: STRIPE_BG } };
        }
        // Number formatting for debit/credit
        if (colNumber === 6 || colNumber === 7) {
          cell.numFmt = '#,##0';
          cell.alignment = { horizontal: 'right', vertical: 'middle' };
          if (cell.value > 0) {
            cell.font = { size: 10, bold: false };
          }
        }
        // Monospace for entry number
        if (colNumber === 3) {
          cell.font = { size: 10, name: 'Consolas' };
        }
        // Center for №
        if (colNumber === 1) {
          cell.alignment = { horizontal: 'center', vertical: 'middle' };
        }
        // Status styling
        if (colNumber === 8) {
          cell.alignment = { horizontal: 'center', vertical: 'middle' };
          const status = String(cell.value).toLowerCase();
          if (status === 'posted') {
            cell.font = { size: 9, bold: true, color: { argb: '166534' } };
          } else if (status === 'draft') {
            cell.font = { size: 9, color: { argb: '92400E' } };
          } else if (status === 'reversed' || status === 'cancelled') {
            cell.font = { size: 9, color: { argb: 'DC2626' } };
          }
        }
      });
    });

    // ── Totals row ──
    const totRow = ws.addRow(['', '', '', '', t('total') || 'Jami:', sumDebit, sumCredit, '']);
    totRow.height = 28;
    totRow.eachCell((cell, colNumber) => {
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: TOTAL_BG } };
      cell.border = { ...borders, top: { ...thickTop } };
      cell.font = { bold: true, size: 11, color: { argb: '1E293B' } };
      cell.alignment = { vertical: 'middle' };
      if (colNumber === 5) {
        cell.alignment = { horizontal: 'right', vertical: 'middle' };
      }
      if (colNumber === 6 || colNumber === 7) {
        cell.numFmt = '#,##0';
        cell.alignment = { horizontal: 'right', vertical: 'middle' };
      }
    });

    // ── Auto-filter on header row ──
    ws.autoFilter = { from: { row: headerRow.number, column: 1 }, to: { row: headerRow.number, column: 8 } };

    // ── Export ──
    const buf = await wb.xlsx.writeBuffer();
    const blob = new Blob([buf], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `jurnal_yozuvlari_${dateFrom || 'all'}_${dateTo || 'all'}.xlsx`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Calculate totals for display
  const totalDebit = newEntry.lines.reduce((sum, line) => sum + parseFloat(line.debit_amount || 0), 0);
  const totalCredit = newEntry.lines.reduce((sum, line) => sum + parseFloat(line.credit_amount || 0), 0);
  const isBalanced = Math.abs(totalDebit - totalCredit) < 0.01;

  const getStatusColor = (status) => {
    const colors = {
      posted: "bg-green-100 text-green-800 border-green-200",
      draft: "bg-yellow-100 text-yellow-800 border-yellow-200",
      reversed: "bg-red-100 text-red-800 border-red-200",
      cancelled: "bg-gray-100 text-gray-600 border-gray-200",
    };
    return colors[status] || "bg-gray-100 text-gray-800";
  };

  const getStatusIcon = (status) => {
    const icons = {
      posted: CheckCircle,
      draft: Clock,
      reversed: ArrowLeftRight,
      cancelled: XCircle,
    };
    const Icon = icons[status] || Clock;
    return <Icon className="w-3 h-3" />;
  };

  // Pagination
  const totalPages = Math.ceil(filteredEntries.length / pageSize);
  const paginatedEntries = filteredEntries.slice((currentPage - 1) * pageSize, currentPage * pageSize);
  const startIndex = (currentPage - 1) * pageSize + 1;
  const endIndex = Math.min(currentPage * pageSize, filteredEntries.length);

  return (
    <div>
      {/* Journal Entries List */}
      <div>
        <Card className="bg-white/80 backdrop-blur-sm border-slate-200/60 shadow-lg">
          <CardHeader className="border-b border-slate-100 pb-6">
            <div className="flex flex-col gap-4">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-[var(--genix-blue)]/10 rounded-xl flex items-center justify-center">
                  <FileText className="w-5 h-5 text-[var(--genix-blue)]" />
                </div>
                <div>
                  <CardTitle className="text-xl font-bold text-slate-900">
                    {t('journal_entries')}
                  </CardTitle>
                  <p className="text-sm text-slate-500 mt-1">
                    {filteredEntries.length} {t('entries_total')}
                  </p>
                </div>
              </div>
              <div className="flex flex-col gap-3">
                {/* Search bar row */}
                <div className="flex flex-col sm:flex-row gap-3">
                  <div className="relative flex-1">
                    <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-slate-400" />
                    <Input
                      placeholder={t('search') + " " + t('journal_entries').toLowerCase() + "..."}
                      className="pl-9 bg-slate-50 border-slate-200 focus:ring-2 focus:ring-[var(--genix-blue)]/20 h-10"
                      value={searchQuery}
                      onChange={(e) => setSearchQuery(e.target.value)}
                    />
                  </div>
                  {canCreate(MODULES.FINANCIALS) && (
                    <Button
                      onClick={() => {
                        resetForm();
                        setNewEntry(prev => ({ ...prev, journal_id: prev.journal_id || defaultJournalId }));
                        setShowCreateModal(true);
                      }}
                      className="bg-gradient-to-r from-[var(--genix-blue)] to-[var(--genix-purple)] hover:opacity-90 transition-opacity shadow-md h-10"
                    >
                      <Plus className="w-4 h-4 mr-2" /> {t('new_entry')}
                    </Button>
                  )}
                </div>

                {/* Always-visible filter row */}
                <div className="flex flex-wrap items-end gap-3 p-3 bg-gradient-to-r from-slate-50 to-blue-50/40 rounded-xl border border-slate-200/80">
                  <div className="space-y-1">
                    <label className="text-xs font-medium text-slate-500 flex items-center gap-1">
                      <Calendar className="w-3 h-3" />
                      {t('from_date') || 'Dan'}
                    </label>
                    <Input
                      type="date"
                      value={dateFrom}
                      onChange={e => setDateFrom(e.target.value)}
                      className="h-9 w-[155px] bg-white border-slate-200 focus:ring-2 focus:ring-[var(--genix-blue)]/20 rounded-lg text-sm"
                    />
                  </div>
                  <div className="flex items-end pb-[6px]">
                    <span className="text-slate-400 text-sm font-medium">—</span>
                  </div>
                  <div className="space-y-1">
                    <label className="text-xs font-medium text-slate-500 flex items-center gap-1">
                      <Calendar className="w-3 h-3" />
                      {t('to_date') || 'Gacha'}
                    </label>
                    <Input
                      type="date"
                      value={dateTo}
                      onChange={e => setDateTo(e.target.value)}
                      className="h-9 w-[155px] bg-white border-slate-200 focus:ring-2 focus:ring-[var(--genix-blue)]/20 rounded-lg text-sm"
                    />
                  </div>
                  <div className="w-px h-8 bg-slate-200 mx-1 self-end mb-[2px] hidden sm:block" />
                  <div className="space-y-1">
                    <label className="text-xs font-medium text-slate-500 flex items-center gap-1">
                      <FileText className="w-3 h-3" />
                      {t('number') || 'Raqam'}
                    </label>
                    <Input
                      placeholder={t('entry_code') || 'Kod...'}
                      value={codeFilter}
                      onChange={e => setCodeFilter(e.target.value)}
                      className="h-9 w-[160px] bg-white border-slate-200 focus:ring-2 focus:ring-[var(--genix-blue)]/20 rounded-lg text-sm"
                    />
                  </div>
                  {activeFilterCount > 0 && (
                    <Button variant="ghost" size="sm" onClick={clearFilters} className="h-9 text-slate-500 hover:text-red-500 gap-1 transition-colors">
                      <X className="w-3.5 h-3.5" />
                      {t('clear') || 'Tozalash'}
                    </Button>
                  )}
                  <div className="flex-1" />
                  <Button
                    onClick={handleExportExcel}
                    className="h-9 gap-2 bg-gradient-to-r from-emerald-500 to-teal-600 hover:from-emerald-600 hover:to-teal-700 text-white shadow-md shadow-emerald-200/50 transition-all duration-200 hover:shadow-lg hover:shadow-emerald-200/60 rounded-lg px-4"
                  >
                    <Download className="w-4 h-4" />
                    <span>{t('export') || 'Export'}</span>
                    <FileSpreadsheet className="w-4 h-4 opacity-70" />
                  </Button>
                </div>
              </div>
            </div>
          </CardHeader>
          <CardContent className="p-0">
            {isLoading ? (
              <div className="flex items-center justify-center py-16">
                <div className="text-center">
                  <div className="w-8 h-8 border-4 border-[var(--genix-blue)] border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
                  <p className="text-slate-600 text-sm">{t('loading')}</p>
                </div>
              </div>
            ) : filteredEntries.length === 0 ? (
              <div className="text-center py-16 px-6">
                <div className="w-20 h-20 bg-gradient-to-br from-slate-100 to-slate-200 rounded-2xl flex items-center justify-center mx-auto mb-6">
                  <FileText className="w-10 h-10 text-slate-400" />
                </div>
                <h3 className="text-lg font-semibold text-slate-900 mb-2">
                  {searchQuery ? t('no_results_found') : t('no_journal_entries')}
                </h3>
                <p className="text-sm text-slate-500 mb-6 max-w-md mx-auto">
                  {searchQuery
                    ? 'Try adjusting your search terms'
                    : 'Start by creating your first journal entry to track financial transactions'}
                </p>
                {!searchQuery && canCreate(MODULES.FINANCIALS) && (
                  <Button
                    onClick={() => {
                      resetForm();
                      setNewEntry(prev => ({ ...prev, journal_id: prev.journal_id || defaultJournalId }));
                      setShowCreateModal(true);
                    }}
                    className="bg-gradient-to-r from-[var(--genix-blue)] to-[var(--genix-purple)]"
                  >
                    <Plus className="w-4 h-4 mr-2" /> {t('create_first_entry')}
                  </Button>
                )}
              </div>
            ) : (
              <>
              <div className="overflow-x-auto">
                <Table className="min-w-[800px]">
                  <TableHeader>
                    <TableRow className="bg-slate-50 hover:bg-slate-50">
                      <TableHead className="font-semibold text-slate-700 w-[110px]">
                        <div className="flex items-center gap-2">
                          <Calendar className="w-4 h-4" />
                          {t('date')}
                        </div>
                      </TableHead>
                      <TableHead className="font-semibold text-slate-700 w-[140px]">{t('number')}</TableHead>
                      <TableHead className="font-semibold text-slate-700">{t('description')}</TableHead>
                      <TableHead className="font-semibold text-slate-700 w-[150px]">{t('journal')}</TableHead>
                      <TableHead className="font-semibold text-slate-700 text-right w-[130px]">
                        <div className="flex items-center justify-end gap-2">
                          <DollarSign className="w-4 h-4" />
                          {t('total')}
                        </div>
                      </TableHead>
                      <TableHead className="font-semibold text-slate-700 w-[120px]">{t('status')}</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {paginatedEntries.map(entry => (
                      <TableRow
                        key={entry.id}
                        onClick={() => handleSelectEntry(entry)}
                        className={`cursor-pointer hover:bg-blue-50/50 transition-colors ${
                          selectedEntry?.id === entry.id ? 'bg-blue-50 border-l-4 border-[var(--genix-blue)]' : ''
                        }`}
                      >
                        <TableCell className="font-medium text-slate-700 whitespace-nowrap">
                          {entry.entry_date ? format(new Date(entry.entry_date), 'dd.MM.yyyy') : '-'}
                        </TableCell>
                        <TableCell className="font-mono text-sm text-slate-600 whitespace-nowrap">{entry.entry_number}</TableCell>
                        <TableCell className="text-slate-700 whitespace-nowrap">
                          {translateJEDescription(entry.description || entry.reference, language) || '-'}
                        </TableCell>
                        <TableCell className="text-slate-600 whitespace-nowrap">
                          {getJournalName(entry.journal, language)}
                        </TableCell>
                        <TableCell className="text-right font-semibold text-slate-900 tabular-nums whitespace-nowrap">
                          {formatCurrency(entry.total_debit || 0)}
                        </TableCell>
                        <TableCell className="whitespace-nowrap">
                          <div className="flex items-center gap-1">
                            <Badge className={`${getStatusColor(entry.reversed_entry_id ? 'reversed' : entry.status)} flex items-center gap-1 w-fit`}>
                              {getStatusIcon(entry.reversed_entry_id ? 'reversed' : entry.status)}
                              {entry.reversed_entry_id ? (t('reversed') || 'reversed') : entry.status}
                            </Badge>
                            {entry.is_reversal && (
                              <Badge variant="outline" className="text-xs">
                                REV
                              </Badge>
                            )}
                          </div>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
              {/* Pagination */}
              {filteredEntries.length > pageSize && (
                <div className="flex items-center justify-between px-4 py-3 border-t border-slate-100">
                  <span className="text-sm text-slate-600">
                    {startIndex}-{endIndex} / {filteredEntries.length}
                  </span>
                  <div className="flex items-center gap-1">
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => setCurrentPage(p => Math.max(1, p - 1))}
                      disabled={currentPage === 1}
                      className="h-8 w-8 p-0"
                    >
                      <ChevronLeft className="h-4 w-4" />
                    </Button>
                    <span className="text-sm text-slate-600 px-2">
                      {currentPage} / {totalPages}
                    </span>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => setCurrentPage(p => Math.min(totalPages, p + 1))}
                      disabled={currentPage === totalPages}
                      className="h-8 w-8 p-0"
                    >
                      <ChevronRight className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
              )}
              </>
            )}
          </CardContent>
        </Card>
      </div>

      {/* Journal Details Sheet (Slide-over drawer) */}
      <Sheet open={!!selectedEntry} onOpenChange={(open) => { if (!open) { setSelectedEntry(null); setSelectedJournalLines([]); } }}>
        <SheetContent side="right" className="w-full sm:max-w-xl overflow-y-auto p-0">
          <SheetHeader className="px-6 pt-6 pb-4 border-b border-slate-100">
            <div className="flex items-center gap-2">
              <FileText className="w-5 h-5 text-[var(--genix-purple)]" />
              <SheetTitle className="text-lg font-bold">
                {t('journal_details')}
              </SheetTitle>
            </div>
            <SheetDescription className="sr-only">{t('journal_details')}</SheetDescription>
          </SheetHeader>
          <div className="p-6">
            {selectedEntry && (
              <div className="space-y-6">
                {/* Entry Header */}
                <div className="pb-4 border-b border-slate-100">
                  <div className="flex items-start justify-between mb-3">
                    <div className="min-w-0 flex-1">
                      <h3 className="font-semibold text-lg text-slate-900 break-words">{translateJEDescription(selectedEntry.description, language)}</h3>
                      <p className="text-sm text-slate-500 font-mono mt-1">#{selectedEntry.entry_number}</p>
                    </div>
                    <div className="flex flex-col items-end gap-1">
                      <Badge className={getStatusColor(selectedEntry.reversed_entry_id ? 'reversed' : selectedEntry.status)}>
                        {selectedEntry.reversed_entry_id ? (t('reversed') || 'reversed') : selectedEntry.status}
                      </Badge>
                      {selectedEntry.is_reversal && (
                        <Badge variant="outline" className="text-xs text-orange-600 border-orange-300">
                          <RotateCcw className="w-3 h-3 mr-1" />
                          {t('reversal_entry') || 'Teskari yozuv'}
                        </Badge>
                      )}
                      {selectedEntry.reversed_entry_id && !selectedEntry.is_reversal && (
                        <Badge variant="outline" className="text-xs text-red-600 border-red-300">
                          {t('has_reversal') || 'Teskarilangan'}
                        </Badge>
                      )}
                    </div>
                  </div>
                  <div className="grid grid-cols-2 gap-3 mt-4">
                    <div className="p-3 bg-slate-50 rounded-lg">
                      <p className="text-xs text-slate-500 mb-1">{t('date')}</p>
                      <p className="text-sm font-semibold text-slate-900">
                        {selectedEntry.entry_date ? format(new Date(selectedEntry.entry_date), 'dd.MM.yyyy') : '-'}
                      </p>
                    </div>
                    <div className="p-3 bg-slate-50 rounded-lg">
                      <p className="text-xs text-slate-500 mb-1">{t('journal')}</p>
                      <p className="text-sm font-semibold text-slate-900">
                        {getJournalName(selectedEntry.journal, language)}
                      </p>
                    </div>
                    {selectedEntry.reference && (
                      <div className="p-3 bg-slate-50 rounded-lg">
                        <p className="text-xs text-slate-500 mb-1">{t('reference')}</p>
                        <p className="text-sm font-semibold text-slate-900">
                          {selectedEntry.reference}
                        </p>
                      </div>
                    )}
                    {selectedEntry.source_type && (
                      <div className="p-3 bg-slate-50 rounded-lg">
                        <p className="text-xs text-slate-500 mb-1">{t('source')}</p>
                        <p className="text-sm font-semibold text-slate-900">
                          {selectedEntry.source_type.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}
                        </p>
                      </div>
                    )}
                    {selectedEntry.reversal_reason && (
                      <div className="p-3 bg-orange-50 rounded-lg col-span-2">
                        <p className="text-xs text-orange-600 mb-1">{t('reversal_reason') || 'Sabab'}</p>
                        <p className="text-sm font-semibold text-orange-900">{selectedEntry.reversal_reason}</p>
                      </div>
                    )}
                  </div>
                  {/* Tags */}
                  {selectedEntry.tags?.length > 0 && (
                    <div className="flex flex-wrap gap-1 mt-3">
                      {selectedEntry.tags.map((tag, i) => (
                        <Badge key={i} variant="outline" className="text-xs">{tag}</Badge>
                      ))}
                    </div>
                  )}
                </div>

                {/* Journal Lines */}
                <div>
                  <h4 className="font-semibold text-slate-900 mb-3 flex items-center gap-2">
                    <DollarSign className="w-4 h-4 text-[var(--genix-blue)]" />
                    {t('journal_lines')}
                  </h4>
                  <div className="space-y-2 max-h-[400px] overflow-y-auto">
                    {isLoadingLines ? (
                      <div className="flex items-center justify-center py-6">
                        <Loader2 className="w-5 h-5 animate-spin text-slate-400" />
                      </div>
                    ) : selectedJournalLines.length > 0 ? (
                      selectedJournalLines.map(line => (
                        <div key={line.id} className="p-3 bg-slate-50 rounded-lg hover:bg-slate-100 transition-colors">
                          <div className="flex justify-between items-start mb-2">
                            <p className="text-sm font-medium text-slate-700 flex-1 pr-2">
                              {line.account ? `${line.account.code} - ${line.account.name}` : line.description}
                            </p>
                          </div>
                          {line.description && line.account && (
                            <p className="text-xs text-slate-500 mb-2">{line.description}</p>
                          )}
                          <div className="grid grid-cols-2 gap-2">
                            <div>
                              <p className="text-xs text-slate-500 mb-1">{t('debit')}</p>
                              <p className="text-sm font-semibold text-green-600 tabular-nums">
                                {line.debit_amount > 0 ? formatCurrency(line.debit_amount) : '-'}
                              </p>
                            </div>
                            <div>
                              <p className="text-xs text-slate-500 mb-1">{t('credit')}</p>
                              <p className="text-sm font-semibold text-red-600 tabular-nums">
                                {line.credit_amount > 0 ? formatCurrency(line.credit_amount) : '-'}
                              </p>
                            </div>
                          </div>
                        </div>
                      ))
                    ) : (
                      <div className="text-center py-6">
                        <p className="text-sm text-slate-500">{t('no_lines_found')}</p>
                      </div>
                    )}
                  </div>
                </div>

                {/* Totals */}
                <div className="pt-4 border-t-2 border-slate-200">
                  <div className="flex justify-between items-center mb-1">
                    <span className="text-sm text-slate-600">{t('total')} {t('debit')}</span>
                    <span className="text-sm font-bold text-green-600 tabular-nums">
                      {formatCurrency(selectedEntry.total_debit || 0)}
                    </span>
                  </div>
                  <div className="flex justify-between items-center">
                    <span className="text-sm text-slate-600">{t('total')} {t('credit')}</span>
                    <span className="text-sm font-bold text-red-600 tabular-nums">
                      {formatCurrency(selectedEntry.total_credit || 0)}
                    </span>
                  </div>
                </div>

                {/* Actions */}
                <div className="space-y-2 pt-2">
                  {/* Draft actions */}
                  {selectedEntry.status === 'draft' && (
                    <>
                      <div className="flex gap-2">
                        <Button
                          className="flex-1 bg-gradient-to-r from-green-500 to-green-600 hover:opacity-90 text-white"
                          onClick={handlePostEntry}
                          disabled={isActionLoading}
                        >
                          <Send className="w-3.5 h-3.5 mr-1.5" />
                          {t('post') || 'Tasdiqlash'}
                        </Button>
                        <Button
                          variant="outline"
                          className="flex-1 text-sm"
                          onClick={handleEditEntry}
                          disabled={isActionLoading}
                        >
                          <Edit className="w-3.5 h-3.5 mr-1.5" />
                          {t('edit')}
                        </Button>
                      </div>
                      <Button
                        variant="outline"
                        className="w-full text-sm text-orange-600 border-orange-200 hover:bg-orange-50"
                        onClick={handleCancelEntry}
                        disabled={isActionLoading}
                      >
                        <XCircle className="w-3.5 h-3.5 mr-1.5" />
                        {t('cancel_entry')}
                      </Button>
                    </>
                  )}
                  {/* Cancelled actions */}
                  {selectedEntry.status === 'cancelled' && (
                    <Button
                      variant="outline"
                      className="w-full text-sm text-red-600 border-red-200 hover:bg-red-50"
                      onClick={handleDeleteEntry}
                      disabled={isActionLoading}
                    >
                      <Trash2 className="w-3.5 h-3.5 mr-1.5" />
                      {t('delete')}
                    </Button>
                  )}
                  {/* Posted actions */}
                  {selectedEntry.status === 'posted' && !selectedEntry.reversed_entry_id && (
                    <Button
                      variant="outline"
                      className="w-full text-sm text-orange-600 border-orange-200 hover:bg-orange-50"
                      onClick={openReverseModal}
                      disabled={isActionLoading}
                    >
                      <RotateCcw className="w-3.5 h-3.5 mr-1.5" />
                      {t('reverse_entry') || 'Teskari yozuv'}
                    </Button>
                  )}
                  {/* Reset to draft (super admins only) — un-post to edit + re-post */}
                  {selectedEntry.status === 'posted' && !selectedEntry.reversed_entry_id && isSuperAdmin && (
                    <Button
                      variant="outline"
                      className="w-full text-sm text-blue-600 border-blue-200 hover:bg-blue-50"
                      onClick={handleResetToDraft}
                      disabled={isActionLoading}
                    >
                      <Pencil className="w-3.5 h-3.5 mr-1.5" />
                      {t('reset_to_draft') || 'Qoralamaga qaytarish'}
                    </Button>
                  )}
                  {/* Always show PDF */}
                  <Button
                    variant="outline"
                    className="w-full text-sm"
                    onClick={handleViewPDF}
                    disabled={isLoadingLines}
                  >
                    <Download className="w-3.5 h-3.5 mr-1.5" />
                    {t('view')} PDF
                  </Button>
                </div>
              </div>
            )}

            {/* Audit Logs */}
            {auditLogs.length > 0 && (
              <div className="mt-4 pt-4 border-t">
                <h3 className="text-sm font-semibold mb-3 flex items-center gap-2">
                  <Clock className="w-4 h-4" />
                  {t('activity_log') || 'Activity Log'}
                </h3>
                <div className="space-y-2">
                  {auditLogs.map((log) => {
                    const actionLabels = {
                      post: { label: t('posted') || 'Posted', color: 'text-green-600 bg-green-50' },
                      cancel: { label: t('cancelled') || 'Cancelled', color: 'text-orange-600 bg-orange-50' },
                      delete: { label: t('deleted') || 'Deleted', color: 'text-red-600 bg-red-50' },
                      create: { label: t('created') || 'Created', color: 'text-blue-600 bg-blue-50' },
                      update: { label: t('updated') || 'Updated', color: 'text-purple-600 bg-purple-50' },
                    };
                    const actionInfo = actionLabels[log.action] || { label: log.action, color: 'text-gray-600 bg-gray-50' };
                    return (
                      <div key={log.id} className="flex items-start gap-3 text-xs p-2 rounded-lg bg-slate-50">
                        <Badge variant="outline" className={`${actionInfo.color} text-xs shrink-0`}>
                          {actionInfo.label}
                        </Badge>
                        <div className="flex-1 min-w-0">
                          <span className="font-medium">{log.user_name}</span>
                          <div className="text-muted-foreground mt-0.5">
                            {format(new Date(log.created_at), 'dd.MM.yyyy HH:mm')}
                          </div>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            )}
          </div>
        </SheetContent>
      </Sheet>

      {/* Create/Edit Journal Entry Modal */}
      <Dialog open={showCreateModal} onOpenChange={(open) => { if (!open) { resetForm(); } setShowCreateModal(open); }}>
        <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="text-xl font-bold flex items-center gap-2">
              <FileText className="w-5 h-5 text-[var(--genix-blue)]" />
              {editingEntryId ? (t('edit') + ' ' + t('journal_entry')) : (t('create') + ' ' + t('journal_entries'))}
            </DialogTitle>
            <DialogDescription>
              {editingEntryId ? (t('edit_journal_entry_description') || 'Edit the draft journal entry') : (t('create_journal_entry_description'))}
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="grid grid-cols-3 gap-4">
              <div>
                <label className="text-sm font-medium text-slate-700 mb-1 block">
                  {t('journal')} *
                </label>
                <Select
                  value={newEntry.journal_id}
                  onValueChange={(value) => setNewEntry({...newEntry, journal_id: value})}
                  disabled={!!editingEntryId}
                >
                  <SelectTrigger>
                    <SelectValue placeholder={t('select_journal')} />
                  </SelectTrigger>
                  <SelectContent>
                    {journals.map((journal) => (
                      <SelectItem key={journal.id} value={journal.id}>
                        {journal.code} - {getJournalName(journal, language)}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div>
                <label className="text-sm font-medium text-slate-700 mb-1 block">
                  {t('date')} *
                </label>
                <Input
                  type="date"
                  value={newEntry.entry_date}
                  onChange={(e) => setNewEntry({...newEntry, entry_date: e.target.value})}
                  required
                />
              </div>
              <div>
                <label className="text-sm font-medium text-slate-700 mb-1 block">
                  {t('reference')}
                </label>
                <Input
                  placeholder={t('reference')}
                  value={newEntry.reference}
                  onChange={(e) => setNewEntry({...newEntry, reference: e.target.value})}
                />
              </div>
            </div>

            <div>
              <label className="text-sm font-medium text-slate-700 mb-1 block">
                {t('description')} *
              </label>
              <Input
                placeholder={t('enter_journal_description')}
                value={newEntry.description}
                onChange={(e) => setNewEntry({...newEntry, description: e.target.value})}
                required
                className={!newEntry.description?.trim() ? 'border-red-300' : ''}
              />
            </div>

            {/* Tags */}
            <div>
              <label className="text-sm font-medium text-slate-700 mb-1 block">
                {t('tags') || 'Teglar'}
              </label>
              <div className="flex items-center gap-2">
                <Input
                  placeholder={t('add_tag') || 'Teg qo\'shing va Enter bosing'}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' && e.target.value.trim()) {
                      e.preventDefault();
                      const tag = e.target.value.trim();
                      if (!newEntry.tags?.includes(tag)) {
                        setNewEntry(prev => ({ ...prev, tags: [...(prev.tags || []), tag] }));
                      }
                      e.target.value = '';
                    }
                  }}
                />
              </div>
              {newEntry.tags?.length > 0 && (
                <div className="flex flex-wrap gap-1 mt-2">
                  {newEntry.tags.map((tag, i) => (
                    <Badge key={i} variant="secondary" className="cursor-pointer" onClick={() => {
                      setNewEntry(prev => ({ ...prev, tags: prev.tags.filter((_, idx) => idx !== i) }));
                    }}>
                      {tag} &times;
                    </Badge>
                  ))}
                </div>
              )}
            </div>

            {/* Journal Lines */}
            <div>
              <div className="flex justify-between items-center mb-2">
                <label className="text-sm font-medium text-slate-700">
                  {t('journal_lines')} *
                </label>
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  onClick={addLine}
                >
                  <Plus className="w-4 h-4 mr-1" />
                  {t('add_line')}
                </Button>
              </div>
              <div className="border rounded-lg overflow-hidden">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead className="w-[35%]">{t('account')}</TableHead>
                      <TableHead className="w-[25%]">{t('description')}</TableHead>
                      <TableHead className="w-[15%] text-right">{t('debit')}</TableHead>
                      <TableHead className="w-[15%] text-right">{t('credit')}</TableHead>
                      <TableHead className="w-[10%]"></TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {newEntry.lines.map((line, index) => (
                      <TableRow key={index}>
                        <TableCell className="p-2">
                          <AccountCombobox
                            accounts={accounts}
                            value={line.account_id}
                            onValueChange={(value) => updateLine(index, 'account_id', value)}
                            placeholder={t('select_account')}
                          />
                        </TableCell>
                        <TableCell className="p-2">
                          <Input
                            className="h-9"
                            placeholder={t('description')}
                            value={line.description}
                            onChange={(e) => updateLine(index, 'description', e.target.value)}
                          />
                        </TableCell>
                        <TableCell className="p-2">
                          <Input
                            className="h-9 text-right"
                            inputMode="decimal"
                            placeholder="0"
                            value={formatNumberInline(line.debit_amount)}
                            onChange={(e) => {
                              const raw = parseFormattedNumber(e.target.value);
                              if (raw === '' || /^\d*\.?\d*$/.test(raw)) {
                                updateLine(index, 'debit_amount', raw);
                              }
                            }}
                          />
                        </TableCell>
                        <TableCell className="p-2">
                          <Input
                            className="h-9 text-right"
                            inputMode="decimal"
                            placeholder="0"
                            value={formatNumberInline(line.credit_amount)}
                            onChange={(e) => {
                              const raw = parseFormattedNumber(e.target.value);
                              if (raw === '' || /^\d*\.?\d*$/.test(raw)) {
                                updateLine(index, 'credit_amount', raw);
                              }
                            }}
                          />
                        </TableCell>
                        <TableCell className="p-2">
                          <Button
                            type="button"
                            variant="ghost"
                            size="sm"
                            onClick={() => removeLine(index)}
                            disabled={newEntry.lines.length <= 2}
                            className="h-9 w-9 p-0"
                          >
                            <Trash2 className="w-4 h-4 text-red-500" />
                          </Button>
                        </TableCell>
                      </TableRow>
                    ))}
                    {/* Totals Row */}
                    <TableRow className="bg-slate-50 font-medium">
                      <TableCell colSpan={2} className="text-right">
                        {t('total')}
                      </TableCell>
                      <TableCell className="text-right tabular-nums">
                        {totalDebit.toLocaleString(undefined, { minimumFractionDigits: 2 })}
                      </TableCell>
                      <TableCell className="text-right tabular-nums">
                        {totalCredit.toLocaleString(undefined, { minimumFractionDigits: 2 })}
                      </TableCell>
                      <TableCell></TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </div>
            </div>

            {/* Balance indicator */}
            <div className={`p-3 rounded-lg flex items-center justify-between ${isBalanced ? 'bg-green-50 border border-green-200' : 'bg-red-50 border border-red-200'}`}>
              <p className={`text-sm font-medium ${isBalanced ? 'text-green-700' : 'text-red-700'}`}>
                {isBalanced ? (
                  <span className="flex items-center gap-2">
                    <CheckCircle className="w-4 h-4" />
                    {t('entry_is_balanced')}
                  </span>
                ) : (
                  <span className="flex items-center gap-2">
                    <AlertCircle className="w-4 h-4" />
                    {t('debits_must_equal_credits')}
                  </span>
                )}
              </p>
              <div className="text-sm tabular-nums">
                <span className="text-green-700 font-medium">Dt: {totalDebit.toLocaleString(undefined, { minimumFractionDigits: 2 })}</span>
                <span className="mx-2 text-slate-400">|</span>
                <span className="text-red-700 font-medium">Kt: {totalCredit.toLocaleString(undefined, { minimumFractionDigits: 2 })}</span>
              </div>
            </div>

            <div className="flex gap-3 pt-4">
              <Button
                variant="outline"
                onClick={() => { resetForm(); setShowCreateModal(false); }}
                className="flex-1"
                disabled={isSaving}
              >
                {t('cancel')}
              </Button>
              <Button
                onClick={handleCreateEntry}
                className="flex-1 bg-gradient-to-r from-[var(--genix-blue)] to-[var(--genix-purple)]"
                disabled={isSaving || !newEntry.journal_id || !newEntry.entry_date || !isBalanced || !newEntry.description?.trim()}
              >
                {isSaving ? t('saving') : (editingEntryId ? t('save') : t('create'))}
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>

      {/* Reverse Entry Modal */}
      <Dialog open={showReverseModal} onOpenChange={setShowReverseModal}>
        <DialogContent className="max-w-lg">
          <DialogHeader>
            <DialogTitle className="text-xl font-bold flex items-center gap-2">
              <RotateCcw className="w-5 h-5 text-orange-500" />
              {t('reverse_entry') || 'Teskari yozuv yaratish'}
            </DialogTitle>
            <DialogDescription>
              {t('reverse_entry_description') || 'Tasdiqlangan yozuvni bekor qilish uchun teskari yozuv yaratiladi'}
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="p-3 bg-slate-50 rounded-lg">
              <p className="text-xs text-slate-500 mb-1">{t('original_entry') || 'Asl yozuv'}</p>
              <p className="text-sm font-semibold text-slate-900">{selectedEntry?.entry_number}</p>
              <p className="text-xs text-slate-500 mt-1">{translateJEDescription(selectedEntry?.description, language)}</p>
            </div>

            <div>
              <label className="text-sm font-medium text-slate-700 mb-1 block">
                {t('date')} *
              </label>
              <Input
                type="date"
                value={reverseDate}
                onChange={(e) => setReverseDate(e.target.value)}
              />
            </div>

            <div>
              <label className="text-sm font-medium text-slate-700 mb-1 block">
                {t('reason') || 'Sabab'}
              </label>
              <Input
                placeholder={t('enter_reversal_reason') || 'Teskari yozuv sababi...'}
                value={reverseReason}
                onChange={(e) => setReverseReason(e.target.value)}
              />
            </div>

            {/* Preview */}
            {selectedJournalLines.length > 0 && (
              <div>
                <p className="text-sm font-medium text-slate-700 mb-2">{t('preview') || 'Natija'}</p>
                <div className="border rounded-lg p-3 bg-orange-50/50 space-y-1">
                  {selectedJournalLines.map((line, i) => (
                    <div key={i} className="flex justify-between text-sm">
                      <span className="text-slate-700">
                        {line.account ? `${line.account.code} - ${line.account.name}` : line.description}
                      </span>
                      <span className="tabular-nums">
                        {line.credit_amount > 0 && <span className="text-green-600">Dt {formatCurrency(line.credit_amount)}</span>}
                        {line.debit_amount > 0 && <span className="text-red-600">Kt {formatCurrency(line.debit_amount)}</span>}
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            <div className="flex gap-3 pt-4">
              <Button
                variant="outline"
                onClick={() => setShowReverseModal(false)}
                className="flex-1"
                disabled={isActionLoading}
              >
                {t('cancel')}
              </Button>
              <Button
                onClick={handleReverseEntry}
                className="flex-1 bg-orange-500 hover:bg-orange-600 text-white"
                disabled={isActionLoading || !reverseDate}
              >
                {isActionLoading ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : <RotateCcw className="w-4 h-4 mr-2" />}
                {t('create_reversal') || 'Teskari yozuv yaratish'}
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>

      <AlertModal modal={modal} close={close} />
    </div>
  );
}
