import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Shield, CheckCircle, AlertTriangle, XCircle, FileText, Globe, Download, Settings } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { useLanguage } from "@/components/contexts/LanguageContext";
import { useTranslation } from "@/components/utils/translations";

export default function CompliancePanel({ compliance }) {
  const { language } = useLanguage();
  const { t } = useTranslation(language);
  const navigate = useNavigate();
  const [showReport, setShowReport] = useState(false);

  React.useEffect(() => {
    return () => setShowReport(false);
  }, []);

  if (!compliance) return null;

  const downloadReport = () => {
    const reportContent = `
COMPLIANCE REPORT
Generated: ${new Date().toLocaleString()}
=====================================

COMPLIANCE STATUS: ${compliance.compliance_status.toUpperCase().replace('_', ' ')}
DETECTED STANDARD: ${compliance.standard_detected}

ISSUES FOUND:
${compliance.issues?.length > 0
  ? compliance.issues.map(i => `- [${i.severity.toUpperCase()}] ${i.issue}\n  Solution: ${i.solution}`).join('\n')
  : '- No issues found'}

RECOMMENDATIONS:
${compliance.recommendations?.map(r => `- ${r}`).join('\n') || '- None'}

=====================================
Generated by Genix ERP
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `compliance-report-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const getStatusIcon = (status) => {
    switch (status) {
      case 'compliant':
        return <CheckCircle className="w-4 h-4 text-emerald-500" />;
      case 'partially_compliant':
        return <AlertTriangle className="w-4 h-4 text-amber-500" />;
      case 'non_compliant':
        return <XCircle className="w-4 h-4 text-red-500" />;
      default:
        return <Shield className="w-4 h-4 text-slate-500" />;
    }
  };

  const getStatusBadge = (status) => {
    const styles = {
      compliant: "bg-emerald-50 text-emerald-700 border-emerald-200",
      partially_compliant: "bg-amber-50 text-amber-700 border-amber-200",
      non_compliant: "bg-red-50 text-red-700 border-red-200"
    };
    return styles[status] || "bg-slate-50 text-slate-700 border-slate-200";
  };

  return (
    <div className="bg-white rounded-2xl border border-slate-100 p-5">
      {/* Header */}
      <div className="flex items-center justify-between mb-5">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-lg bg-indigo-50 flex items-center justify-center">
            <Shield className="w-4 h-4 text-indigo-600" />
          </div>
          <h3 className="text-sm font-semibold text-slate-900">{t('compliance_status')}</h3>
        </div>
        <div className="flex items-center gap-2">
          <span className={`inline-flex items-center gap-1.5 text-xs font-medium px-2.5 py-1 rounded-full border ${getStatusBadge(compliance.compliance_status)}`}>
            {getStatusIcon(compliance.compliance_status)}
            {t(compliance.compliance_status) || compliance.compliance_status.replace('_', ' ')}
          </span>
          <span className="inline-flex items-center gap-1 text-xs font-medium text-slate-600 bg-slate-50 px-2.5 py-1 rounded-full border border-slate-200">
            <Globe className="w-3 h-3" />
            {compliance.standard_detected}
          </span>
        </div>
      </div>

      {/* Two columns: Standard + Best Practices */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-5">
        <div className="p-4 bg-slate-50 rounded-xl">
          <div className="flex items-center gap-2 mb-2">
            <FileText className="w-4 h-4 text-slate-500" />
            <h4 className="text-sm font-semibold text-slate-800">{t('detected_standard')}</h4>
          </div>
          <p className="text-xs text-slate-500 leading-relaxed">
            {compliance.standard_detected === 'IFRS' && t('ifrs_description')}
            {compliance.standard_detected === 'US_GAAP' && t('us_gaap_description')}
            {compliance.standard_detected === 'MIXED' && t('mixed_standards_description')}
          </p>
        </div>

        <div className="p-4 bg-slate-50 rounded-xl">
          <div className="flex items-center gap-2 mb-2">
            <CheckCircle className="w-4 h-4 text-emerald-500" />
            <h4 className="text-sm font-semibold text-slate-800">{t('best_practices')}</h4>
          </div>
          <ul className="text-xs text-slate-500 space-y-1.5">
            <li className="flex items-start gap-1.5">
              <span className="text-slate-300 mt-0.5">•</span>
              {t('best_practice_fifo')}
            </li>
            <li className="flex items-start gap-1.5">
              <span className="text-slate-300 mt-0.5">•</span>
              {t('best_practice_audit')}
            </li>
            <li className="flex items-start gap-1.5">
              <span className="text-slate-300 mt-0.5">•</span>
              {t('best_practice_cogs')}
            </li>
            <li className="flex items-start gap-1.5">
              <span className="text-slate-300 mt-0.5">•</span>
              {t('best_practice_valuation')}
            </li>
          </ul>
        </div>
      </div>

      {/* Issues */}
      {compliance.issues && compliance.issues.length > 0 && (
        <div className="mb-5">
          <h4 className="text-sm font-semibold text-slate-800 mb-3">{t('compliance_issues')}</h4>
          <div className="space-y-2">
            {compliance.issues.map((issue, index) => (
              <div key={index} className="flex items-start gap-3 p-3 rounded-xl bg-amber-50/60 border border-amber-100">
                <AlertTriangle className="w-4 h-4 text-amber-500 mt-0.5 shrink-0" />
                <div>
                  <p className="text-sm font-medium text-slate-800">{issue.issue}</p>
                  <p className="text-xs text-slate-500 mt-0.5">{issue.solution}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Recommendations */}
      {compliance.recommendations && compliance.recommendations.length > 0 && (
        <div className="mb-5">
          <h4 className="text-sm font-semibold text-slate-800 mb-3">{t('recommendations')}</h4>
          <div className="p-4 bg-emerald-50/50 rounded-xl border border-emerald-100/50">
            <ul className="space-y-2">
              {compliance.recommendations.map((rec, index) => (
                <li key={index} className="flex items-start gap-2 text-xs text-slate-600">
                  <CheckCircle className="w-3.5 h-3.5 text-emerald-500 mt-0.5 shrink-0" />
                  <span>{rec}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      )}

      {/* Action Buttons */}
      <div className="flex gap-3 pt-4 border-t border-slate-100">
        <button
          onClick={() => setShowReport(true)}
          className="flex-1 inline-flex items-center justify-center gap-2 text-sm font-medium text-slate-700 bg-white border border-slate-200 hover:bg-slate-50 px-4 py-2.5 rounded-xl transition-colors"
        >
          <FileText className="w-4 h-4" />
          {t('generate_compliance_report')}
        </button>
        <button
          onClick={() => navigate('/adminsettings?tab=inventory')}
          className="flex-1 inline-flex items-center justify-center gap-2 text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 px-4 py-2.5 rounded-xl transition-colors"
        >
          <Settings className="w-4 h-4" />
          {t('review_settings')}
        </button>
      </div>

      {/* Report Modal */}
      <Dialog open={showReport} onOpenChange={setShowReport}>
        <DialogContent className="sm:max-w-lg">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <FileText className="w-5 h-5 text-indigo-600" />
              {t('compliance_report')}
            </DialogTitle>
            <DialogDescription>
              {t('generated_on')} {new Date().toLocaleDateString()}
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="p-4 bg-slate-50 rounded-xl space-y-3">
              <div className="flex justify-between items-center">
                <span className="text-sm font-medium text-slate-600">{t('status')}:</span>
                <span className={`inline-flex items-center gap-1.5 text-xs font-medium px-2.5 py-1 rounded-full border ${getStatusBadge(compliance.compliance_status)}`}>
                  {t(compliance.compliance_status) || compliance.compliance_status.replace('_', ' ')}
                </span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-sm font-medium text-slate-600">{t('accounting_standard')}:</span>
                <span className="text-xs font-medium text-slate-600 bg-white px-2.5 py-1 rounded-full border border-slate-200">{compliance.standard_detected}</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-sm font-medium text-slate-600">{t('issues_found')}:</span>
                <span className="text-sm text-slate-800">{compliance.issues?.length || 0}</span>
              </div>
            </div>

            {compliance.issues?.length > 0 && (
              <div>
                <h4 className="text-sm font-medium text-slate-800 mb-2">{t('compliance_issues')}:</h4>
                {compliance.issues.map((issue, idx) => (
                  <div key={idx} className="p-3 bg-amber-50 border border-amber-100 rounded-xl text-sm mb-2">
                    <p className="font-medium text-amber-800">{issue.issue}</p>
                    <p className="text-amber-600 text-xs mt-1">{issue.solution}</p>
                  </div>
                ))}
              </div>
            )}
          </div>
          <div className="flex gap-3">
            <Button variant="outline" className="flex-1 rounded-xl" onClick={() => setShowReport(false)}>
              {t('close')}
            </Button>
            <Button className="flex-1 rounded-xl" onClick={downloadReport}>
              <Download className="w-4 h-4 mr-2" />
              {t('download_report')}
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
