import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Shield, CheckCircle, AlertTriangle, XCircle, FileText, Globe, Download, Settings, X } from "lucide-react";
import { Alert, AlertDescription } from "@/components/ui/alert";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { useLanguage } from "@/components/contexts/LanguageContext";
import { useTranslation } from "@/components/utils/translations";

export default function CompliancePanel({ compliance }) {
  const { language } = useLanguage();
  const { t } = useTranslation(language);
  const [showReport, setShowReport] = useState(false);
  const [showSettings, setShowSettings] = useState(false);

  // Cleanup on unmount to prevent blocking navigation
  React.useEffect(() => {
    return () => {
      setShowReport(false);
      setShowSettings(false);
    };
  }, []);

  if (!compliance) return null;

  const generateReport = () => {
    setShowReport(true);
  };

  const downloadReport = () => {
    const reportContent = `
COMPLIANCE REPORT
Generated: ${new Date().toLocaleString()}
=====================================

COMPLIANCE STATUS: ${compliance.compliance_status.toUpperCase().replace('_', ' ')}
DETECTED STANDARD: ${compliance.standard_detected}

ISSUES FOUND:
${compliance.issues?.length > 0
  ? compliance.issues.map(i => `- [${i.severity.toUpperCase()}] ${i.issue}\n  Solution: ${i.solution}`).join('\n')
  : '- No issues found'}

RECOMMENDATIONS:
${compliance.recommendations?.map(r => `- ${r}`).join('\n') || '- None'}

=====================================
Generated by Genix ERP
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `compliance-report-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const getStatusIcon = (status) => {
    switch (status) {
      case 'compliant':
        return <CheckCircle className="w-5 h-5 text-green-500" />;
      case 'partially_compliant':
        return <AlertTriangle className="w-5 h-5 text-yellow-500" />;
      case 'non_compliant':
        return <XCircle className="w-5 h-5 text-red-500" />;
      default:
        return <Shield className="w-5 h-5 text-slate-500" />;
    }
  };

  const getStatusColor = (status) => {
    const colors = {
      compliant: "bg-green-100 text-green-800",
      partially_compliant: "bg-yellow-100 text-yellow-800",
      non_compliant: "bg-red-100 text-red-800"
    };
    return colors[status] || "bg-slate-100 text-slate-800";
  };

  const getSeverityColor = (severity) => {
    const colors = {
      critical: "bg-red-100 text-red-800 border-red-200",
      warning: "bg-yellow-100 text-yellow-800 border-yellow-200",
      info: "bg-blue-100 text-blue-800 border-blue-200"
    };
    return colors[severity] || "bg-slate-100 text-slate-800";
  };

  return (
    <Card className="bg-white/80 backdrop-blur-sm border-slate-200/60 shadow-lg">
      <CardHeader>
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Shield className="w-5 h-5 text-[var(--genix-blue)]" />
            <CardTitle>{t('compliance_status')}</CardTitle>
          </div>
          <div className="flex items-center gap-3">
            <Badge className={getStatusColor(compliance.compliance_status)}>
              {getStatusIcon(compliance.compliance_status)}
              <span className="ml-1">{compliance.compliance_status.replace('_', ' ')}</span>
            </Badge>
            <Badge variant="outline" className="flex items-center gap-1">
              <Globe className="w-3 h-3" />
              {compliance.standard_detected}
            </Badge>
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-6">
        
        {/* Compliance Overview */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="p-4 bg-slate-50 rounded-lg">
            <div className="flex items-center gap-2 mb-2">
              <FileText className="w-4 h-4 text-slate-600" />
              <h4 className="font-semibold">{t('detected_standard')}</h4>
            </div>
            <p className="text-sm text-slate-600">
              {compliance.standard_detected === 'IFRS' && t('ifrs_description')}
              {compliance.standard_detected === 'US_GAAP' && t('us_gaap_description')}
              {compliance.standard_detected === 'MIXED' && t('mixed_standards_description')}
            </p>
          </div>

          <div className="p-4 bg-slate-50 rounded-lg">
            <div className="flex items-center gap-2 mb-2">
              <CheckCircle className="w-4 h-4 text-green-600" />
              <h4 className="font-semibold">{t('best_practices')}</h4>
            </div>
            <ul className="text-sm text-slate-600 space-y-1">
              <li>• {t('best_practice_fifo')}</li>
              <li>• {t('best_practice_audit')}</li>
              <li>• {t('best_practice_cogs')}</li>
              <li>• {t('best_practice_valuation')}</li>
            </ul>
          </div>
        </div>

        {/* Issues & Recommendations */}
        {compliance.issues && compliance.issues.length > 0 && (
          <div>
            <h4 className="font-semibold mb-3">{t('compliance_issues')}</h4>
            <div className="space-y-3">
              {compliance.issues.map((issue, index) => (
                <Alert key={index} className={getSeverityColor(issue.severity)}>
                  <AlertTriangle className="h-4 w-4" />
                  <AlertDescription>
                    <div className="font-medium mb-1">{issue.issue}</div>
                    <div className="text-sm opacity-90">Solution: {issue.solution}</div>
                  </AlertDescription>
                </Alert>
              ))}
            </div>
          </div>
        )}

        {/* Recommendations */}
        {compliance.recommendations && compliance.recommendations.length > 0 && (
          <div>
            <h4 className="font-semibold mb-3">{t('recommendations')}</h4>
            <div className="bg-blue-50 rounded-lg p-4">
              <ul className="space-y-2">
                {compliance.recommendations.map((rec, index) => (
                  <li key={index} className="flex items-start gap-2 text-sm">
                    <CheckCircle className="w-4 h-4 text-blue-600 mt-0.5 flex-shrink-0" />
                    <span>{rec}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        )}

        {/* Action Buttons */}
        <div className="flex gap-3 pt-4 border-t">
          <Button variant="outline" className="flex-1" onClick={generateReport}>
            <FileText className="w-4 h-4 mr-2" />
            {t('generate_compliance_report')}
          </Button>
          <Button
            className="flex-1 bg-gradient-to-r from-[var(--genix-blue)] to-[var(--genix-purple)]"
            onClick={() => setShowSettings(true)}
          >
            <Settings className="w-4 h-4 mr-2" />
            {t('review_settings')}
          </Button>
        </div>

      </CardContent>

      {/* Report Modal */}
      <Dialog open={showReport} onOpenChange={setShowReport}>
        <DialogContent className="sm:max-w-lg">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <FileText className="w-5 h-5 text-[var(--genix-blue)]" />
              {t('compliance_report')}
            </DialogTitle>
            <DialogDescription>
              {t('generated_on')} {new Date().toLocaleDateString()}
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="p-4 bg-slate-50 rounded-lg space-y-3">
              <div className="flex justify-between items-center">
                <span className="font-medium">{t('status')}:</span>
                <Badge className={getStatusColor(compliance.compliance_status)}>
                  {compliance.compliance_status.replace('_', ' ')}
                </Badge>
              </div>
              <div className="flex justify-between items-center">
                <span className="font-medium">{t('accounting_standard')}:</span>
                <Badge variant="outline">{compliance.standard_detected}</Badge>
              </div>
              <div className="flex justify-between items-center">
                <span className="font-medium">{t('issues_found')}:</span>
                <span>{compliance.issues?.length || 0}</span>
              </div>
            </div>

            {compliance.issues?.length > 0 && (
              <div>
                <h4 className="font-medium mb-2">{t('compliance_issues')}:</h4>
                {compliance.issues.map((issue, idx) => (
                  <div key={idx} className="p-3 bg-yellow-50 border border-yellow-200 rounded-lg text-sm mb-2">
                    <p className="font-medium text-yellow-800">{issue.issue}</p>
                    <p className="text-yellow-700 mt-1">{issue.solution}</p>
                  </div>
                ))}
              </div>
            )}
          </div>
          <div className="flex gap-3">
            <Button variant="outline" className="flex-1" onClick={() => setShowReport(false)}>
              {t('close')}
            </Button>
            <Button className="flex-1" onClick={downloadReport}>
              <Download className="w-4 h-4 mr-2" />
              {t('download_report')}
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      {/* Settings Modal */}
      <Dialog open={showSettings} onOpenChange={setShowSettings}>
        <DialogContent className="sm:max-w-lg">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Settings className="w-5 h-5 text-[var(--genix-blue)]" />
              {t('compliance_settings')}
            </DialogTitle>
            <DialogDescription>
              {t('compliance_settings_description')}
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="p-4 bg-slate-50 rounded-lg">
              <h4 className="font-medium mb-3">{t('current_configuration')}</h4>
              <div className="space-y-2 text-sm">
                <div className="flex justify-between">
                  <span className="text-slate-600">{t('accounting_standard')}:</span>
                  <span className="font-medium">{compliance.standard_detected}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-600">{t('default_costing_method')}:</span>
                  <span className="font-medium">FIFO</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-600">{t('audit_trail')}:</span>
                  <span className="font-medium text-green-600">{t('enabled')}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-600">{t('auto_compliance_check')}:</span>
                  <span className="font-medium text-green-600">{t('enabled')}</span>
                </div>
              </div>
            </div>

            <div className="p-4 bg-blue-50 rounded-lg">
              <p className="text-sm text-blue-800">
                <strong>{t('note')}:</strong> {t('compliance_settings_note')}
              </p>
            </div>
          </div>
          <div className="flex gap-3">
            <Button variant="outline" className="flex-1" onClick={() => setShowSettings(false)}>
              {t('close')}
            </Button>
            <Button className="flex-1" disabled>
              <Shield className="w-4 h-4 mr-2" />
              {t('save_settings')}
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </Card>
  );
}